name: Deploy Widget to VPS
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
                cd /var/www/calmflo-widget || exit 1
                git fetch origin main || exit 1
                git reset --hard origin/main || exit 1
                npm ci || exit 1
                npm run build || exit 1
